"""empty message

Revision ID: 715e39f20310
Revises: 003d1677791a
Create Date: 2022-01-15 22:25:41.933357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715e39f20310'
down_revision = '003d1677791a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('mdatetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_board')
    # ### end Alembic commands ###
